version: "3.9"
services:
  ftp: 
    build: .
    ports:
      - 10021:21
      - 10090-10100:10090-10100
    volumes:
      - ftpdata:/home/reolink
    environment:
      - FTP_USER=reolink      
    env_file:
      - .env
    restart: always
volumes:
  ftpdata:
